djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from django.urls import include, path

from links import views as linkviews

from links.views import  LinkDetailView, LinkUpdateView, LinkDeleteView

# (P<pk>\d+) used to get primary key of link 
urlpatterns = [
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('signup/', linkviews.signup, name='signup'),
    path('admin/', admin.site.urls),
    path('links/create/', login_required(linkviews.link_create), name='link_create'),
    path('link/(P<pk>\d+)/', LinkDetailView.as_view(), name='link_detail'),
    path('links/delete/(P<pk>\d+)', login_required(LinkDeleteView.as_view()), name='link_delete'),
    path('links/update/(P<pk>\d+)/', login_required(LinkUpdateView.as_view()), name='link_update'),
    path('comment/(P<pk>\d+)', linkviews.link_comment, name='link_comment'),
    path('reply/(P<pk>\d+)', linkviews.reply_comment, name='reply_comment'),
    path('vote/', login_required(linkviews.updoot), name='vote'),
    path('', include('links.urls'))
]

djangoproject/links/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home')
]

djangoproject/links/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Link(models.Model):
    title = models.CharField("Headline", max_length=100)
    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    rank = models.IntegerField(default = 0)
    url = models.URLField("URL", max_length=250, blank=True)
    description = models.TextField(blank=True)

    # Get top level comment
    def get_parent(self):
        return self.comments.filter(parent__isnull=True)

    # URL to Link Page
    def get_absolute_url(self):
        return reverse("link_detail", kwargs={"pk": str(self.id)})

    def __str__(self):
        return self.title

class Vote(models.Model):
    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    link = models.ForeignKey(Link, on_delete=models.CASCADE)

    def __str__(self):
        return "%s upvoted %s" % (self.voter.username, self.link.title)

class Comment(models.Model):
    link = models.ForeignKey(Link, on_delete=models.CASCADE, related_name='comments')
    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', null=True)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __str__(self):
        return self.text

djangoproject/links/forms.py
from django import forms

from .models import Link, Comment, Vote

# Create/Edit Link
class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ("submitter", "rank")

# Comment/Reply
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

#Updoot
class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = '__all__'

djangoproject/links/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Link, Vote, Comment

from .forms import LinkForm, CommentForm, VoteForm

# Create your views here.

# Home Page
def index(request):

    # Get all Links and Order them (descending by votes)
    linkList = Link.objects.all().order_by('-vote')

    # Pagination - Alter second argument to change number of links per page
    paginator = Paginator(linkList, 10)

    # Separating Links based on pagination arguments
    page = request.GET.get('page')
    links = paginator.get_page(page)

    context = {
        'links': links
    }

    return render(request, 'links/index.html', context)

def link_delete(request):
    link = Link.objects.get(pk)
    link.delete()
 
# Register - Sign Up
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()

            # Get username
            username = form.cleaned_data.get('username')

            # Get password
            raw_password = form.cleaned_data.get('password1')

            # Log In
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            # Redirect to home page
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

# Reply to Comment
def reply_comment(request, pk):

    # Get parent link
    parent = get_object_or_404(Comment, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            # Do not commit save (variables still need assignment)
            comment = form.save(commit=False)

            # Reply's parent comment
            comment.parent = parent

            # Associated link
            comment.link = parent.link

            # Commenter
            comment.submitter = request.user

            # Commit
            comment.save()
            return redirect('link_detail', pk=parent.link.pk)
    else:
        form = CommentForm()
    return render(request, 'links/link_comment.html', {'form': form})

# Comment on Link (top level)
def link_comment(request, pk):

    # Get associated link
    link = get_object_or_404(Link, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            # Do not commit save (variables still need assignment)
            comment = form.save(commit=False)

            # Associated link
            comment.link = link

            # Commenter
            comment.submitter = request.user

            # Commit
            comment.save()
            return redirect('link_detail', pk=pk)
    else:
        form = CommentForm()
    return render(request, 'links/link_comment.html', {'form': form})

# Create a link
def link_create(request):
    if request.method == 'POST':
        form = LinkForm(request.POST)

        if form.is_valid():
            # Do not commit save (variables still need assignment)
            link = form.save(commit=False)

            # Default Updoots = 0
            link.rank_score = 0

            # Submitter
            link.submitter = request.user

            # Commit
            link.save()
            return redirect('link_detail', pk=link.id)
    else:
        form = LinkForm()
    return render(request, 'links/link_form.html', {'form': form})

# Handles the Updoots
def updoot(request):

    # Get form
    form = VoteForm(request.POST)

    # Get link
    link = get_object_or_404(Link, pk=form.data["link"])

    # Get voter
    user = request.user

    # How many times has this user updooted this link
    has_voted = Vote.objects.filter(voter=user, link=link)

    # Only updoot if user never updooted before
    if has_voted.count() == 0:
        # Has not voted this link -> allow updoot
        Vote.objects.create(voter=user, link=link)
    else:
        # User has changed his mind (had already voted) -> delete updoot
        has_voted[0].delete()
    return redirect('home')

# Link Page
class LinkDetailView(DetailView):
    model = Link

# Edit Page
class LinkUpdateView(UpdateView):
    model = Link
    # Use same form as Link creation 
    form_class = LinkForm

# Delete Page
class LinkDeleteView(DeleteView):
    model = Link
    # Return to home page after deletion successful
    success_url = reverse_lazy('home')

djangoproject/links/templates/layout.html
<!DOCTYPE html>
<head>
    <meta charset='UTF-8'>
    <meta name='viewpoint' content='width=device-width, initial-scale=1.0'>
    <!--Materialize CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <!--Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>KronoPost</title>

    <!--jQuery and Materialize CSS functions-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
</head>

<body>
    <header>
        <!--Navigation Bar-->
        <nav class="blue lighten-1" role="navigation">
            <div class="nav-wrapper container">
                <ul id="nav-mobile" class="sidenav">
                    <li><a href="{% url 'signup' %}">Register</a></li>
                </ul>
                <ul id="nav-mobile" class="sidenav">
                    <li><a href="{% url 'login' %}">Login</a></li>
                </ul>
                <ul id="nav-mobile" class="sidenav">
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>

                <ul id="nav-mobile" class="sidenav center">
                        <li><a href="{% url 'home' %}" class="brand-logo center">KronoPost</a></li>
                </ul>
                
                <ul id="nav-mobile" class="sidenav right">
                    <li>
                        <!--Signed In users have their name displayed and can create posts-->
                        {% if user.is_authenticated %}
                            {{user.get_username}}
                            <ul id="nav-mobile" class="sidenav right">
                                <!--Create Post-->
                                <li><a class="btn btn-floating blue pulse" href="{% url 'link_create' %}"><i class="material-icons">edit</i></a></li>
                            </ul>
                        {% else %}
                            Anonymous User
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class='container'>
        <!--Templates get loaded here-->
        {% block content%}
        {% endblock%}
    </div>
    <footer>
            <ul class='pagination'>
                <!--Creates icon if there are previous pages-->
                {% if links.has_previous %}
                    <li class='waves-effect'>
                        <a href='?page={{ links.previous_page_number }}'><i class="material-icons">chevron_left</i></a>
                    </li>
                {% endif %}
        
                <!--Pagination-->
                {% for i in links.paginator.page_range %}
                    {% if links.number == i %}
                        <li class='active waves-effect btn blue lighten-1'><span>{{ i }}</span></li>
                    {% else %}
                        <li  class='waves-effect btn-flat'><a href='?page={{ i }}'>{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                
                <!--Creates icon if there are more pages-->
                {% if links.has_next %}
                    <li class='waves-effect'>
                        <a href='?page={{ links.next_page_number }}'><i class="material-icons">chevron_right</i></a>
                    </li>
                {% endif %}
            </ul>
    </footer>
</body>

djangoproject/links/templates/links/index.html
{% extends 'layout.html' %}

{% block content %}
<ul class='center-align'>
    {% for link in links %}
    <!-- Form used to make updoot button-->
    <form method='POST' action="{% url 'vote' %}" class='vote_form'>
        <li class='card-panel hoverable'>
            {% csrf_token %}
            <input type='hidden' id='id_link' name='link' value='{{link.pk}}'/>
            <input type='hidden' id='id_voter' name='voter' value='{{user.pk}}'/>
            <button class="btn-floating green accent-4 left"><i class="material-icons">arrow_upward</i></button>
            <a href='{{link.get_absolute_url}}'>
                <b>{{link.title}}</b> [{{link.comments.count}} comments]
            </a>
        </li>
    </form>
    {% endfor %}
</ul>
{% endblock %}

djangoproject/links/templates/links/link_comment.html
{% extends 'layout.html' %}

{% block content %}
<h2>Comment</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class='waves-effect waves-light btn blue lighten-1'>Comment</button>
</form>
{% endblock %}

djangoproject/links/templates/links/link_confirm_delete.html
{% extends "layout.html" %}

{% block content %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post" action="{% url 'link_delete' pk=object.pk %}">
  {% csrf_token %}
  <!--Go Back-->
  <a href="{% url 'link_detail' pk=object.pk %}" class='waves-effect waves-light btn blue lighten-1'><i class="material-icons">arrow_back</i></a> 
  <!--CConfirm-->
  <p><input type="submit" value="Confirm deletion" class='waves-effect waves-light btn red' /></p>
</form> 

{% endblock %}

djangoproject/links/templates/links/link_detail.html
{% extends 'layout.html' %}

{% block content %}
<!--Link Header-->
<h2>{{ object.title }}</h2>
<!--Link URL-->
<h5><a href='{{ object.url }}'>{{object.url}}</a></h5>
<!--Link Original Poster-->
<p>Submitted by: {{object.submitter}}</p>

<!--Link Options (OP only)-->
{% if object.submitter == user %}
<div class="fixed-action-btn vertical click-to-toggle left">
    <a class="btn-floating btn-large yellow darken-2">
        <i class="large material-icons">build</i>
    </a>
    <ul>
        <!--Link Edit-->
        <li><a class="btn-floating blue darken-1" href="{% url 'link_update' pk=object.pk %}"><i class="material-icons">mode_edit</i></a></li>
        <!--Link Delete-->
        <li><a class="btn-floating red" href="{% url 'link_delete' pk=object.pk %}"><i class="material-icons">delete</i></a></li>
    </ul>
</div>
{% endif %}
<!--Link Description-->
<div class="card-panel">
        {{object.description}}
</div>

<!--Comment Button-->
{% if user.is_authenticated %}
    <a class="btn btn-floating yellow darken-1" href="{% url 'link_comment' pk=object.pk %}"><i class="material-icons">comment</i></a>
{% else %}
    <h5>You must be logged in to comment</h5>
{% endif %}

<!--Comments-->
{% for comment in object.get_parent %}
    {%include 'links/link_reply.html'%}
{% empty %}
    <p>No comments yet</p>
{% endfor %}

{% endblock %}

djangoproject/links/templates/links/link_form.html
{% extends 'layout.html' %}

{% block content %}
  <h2>Create Post</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class='waves-effect waves-light btn blue lighten-1'>Create</button>
  </form>
{% endblock %}

djangoproject/links/templates/links/link_reply.html
<!--This gets called to show threaded comments/replies-->
<div class='card-panel'>
    <p>{{comment.submitter}} on {{comment.date}}</p>
    <p>{{comment.text}}</p>

    <!--Signed In users can reply-->
    {% if user.is_authenticated %}
        <a href="{% url 'reply_comment' pk=comment.pk %}">reply</a>
    {% endif %}

    <!--Replies (if existant)-->
    {% if comment.children %}
            <!--Recursively call this html to showcase all replies-->
            {% for comment in comment.children.all %}
                {% include 'links/link_reply.html' %}
            {% endfor %}
    {% endif %}
</div>